name: SEPstudy
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterhub
  - pip
  - pip:
    - jupyter
    - h5py
    - pandas
    - python-time
    - argparse
    - tqdm
    - tensorflow==2.4.0
    - tensorflow_datasets
    - qkeras==0.9.0
    - scikit-learn
    - seaborn
    - matplotlib
